language: java

jdk:
  - oraclejdk8
  
services:
  - mysql
  
before_script:
- mysql -u root -e 'CREATE DATABASE librarymanager;'
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

after_success:
  - mvn clean test jacoco:report coveralls:report